export const AVATARS = [
  { emoji: "🧉", label: "Mate",      anim: "bounce", speed: "1.2s" },
  { emoji: "🦫", label: "Carpincho", anim: "bounce", speed: "1.5s" },
  { emoji: "♨️", label: "Termo",     anim: "pulse",  speed: "1.8s" },
  { emoji: "🌿", label: "Yerba",     anim: "pulse",  speed: "2s"   },
  { emoji: "🎸", label: "Guitarra",  anim: "bounce", speed: "1s"   },
  { emoji: "📚", label: "Libros",    anim: "pulse",  speed: "2.2s" },
  { emoji: "💻", label: "Compu",     anim: "pulse",  speed: "2s"   },
  { emoji: "🎨", label: "Arte",      anim: "bounce", speed: "1.3s" },
  { emoji: "🎮", label: "Gamer",     anim: "bounce", speed: "1.1s" },
  { emoji: "🔬", label: "Ciencia",   anim: "pulse",  speed: "2.4s" },
  { emoji: "🦊", label: "Zorro",     anim: "bounce", speed: "1.4s" },
  { emoji: "🐸", label: "Sapo",      anim: "bounce", speed: "1.2s" },
  { emoji: "🐼", label: "Panda",     anim: "pulse",  speed: "2s"   },
  { emoji: "🦉", label: "Búho",      anim: "pulse",  speed: "2.6s" },
  { emoji: "🦁", label: "León",      anim: "bounce", speed: "1.5s" },
  { emoji: "🐨", label: "Koala",     anim: "pulse",  speed: "2.2s" },
  { emoji: "🐵", label: "Mono",      anim: "bounce", speed: "1.1s" },
  { emoji: "🦝", label: "Mapache",   anim: "bounce", speed: "1.3s" },
  { emoji: "🐙", label: "Pulpo",     anim: "pulse",  speed: "2s"   },
  { emoji: "🦄", label: "Unicornio", anim: "bounce", speed: "1.4s" },
  { emoji: "🐉", label: "Dragón",    anim: "pulse",  speed: "2.5s" },
  { emoji: "👽", label: "Alien",     anim: "bounce", speed: "1.3s" },
  { emoji: "🤖", label: "Robot",     anim: "pulse",  speed: "1.8s" },
  { emoji: "🥷", label: "Ninja",     anim: "bounce", speed: "1.2s" },
  { emoji: "🧠", label: "Cerebro",   anim: "pulse",  speed: "2s"   },
  { emoji: "🚀", label: "Cohete",    anim: "bounce", speed: "1s"   },
  { emoji: "⭐", label: "Estrella",  anim: "pulse",  speed: "1.6s" },
  { emoji: "🔥", label: "Fuego",     anim: "pulse",  speed: "1.4s" },
  { emoji: "🌵", label: "Cactus",    anim: "pulse",  speed: "2.4s" },
  { emoji: "🍄", label: "Hongo",     anim: "bounce", speed: "1.5s" },
];

export type AvatarEmoji = typeof AVATARS[number]["emoji"];
